name: Coverage Report
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - name: Install
        run: yarn
      - name: Get previous coverage
        id: previous_coverage_percentage
        shell: bash -ex {0}
        run: |
          PERCENTAGE=$(node -p 'require("./coverage/coverage-summary.json").total.statements.pct')
          echo "::set-output name=PERCENTAGE::$PERCENTAGE"
      - name: Generate and commit report
        run: |
          yarn test:coverage
          git config --global user.name github-actions
          git config --global user.email github-actions@users.noreply.github.com
          git commit -am "Automated coverage report"
          git push
      - name: Get new coverage
        id: coverage_percentage
        shell: bash -ex {0}
        run: |
          PERCENTAGE=$(node -p 'require("./coverage/coverage-summary.json").total.statements.pct')
          echo "::set-output name=PERCENTAGE::$PERCENTAGE"
      - if: steps.previous_coverage_percentage.outputs.PERCENTAGE != steps.coverage_percentage.outputs.PERCENTAGE
        name: Generate and commit badges
        run: |
          yarn test:badges
          git commit -am "Automated coverage badges"
          git push
      - if: steps.coverage_percentage.outputs.PERCENTAGE < 80
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Code coverage is too low. Current coverage is ${{steps.coverage_percentage.outputs.PERCENTAGE}}%. Minimum required coverage is 80%.'
            })
      - if: steps.coverage_percentage.outputs.PERCENTAGE < 80
        run: exit 1
