name: Coverage Report
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Run tests
        run: yarn test:coverage
      - name: Check coverage
        id: coverage_percentage
        shell: bash -ex {0}
        run: |
          PERCENTAGE=$(node -p 'require("./coverage/coverage-summary.json").total.statements.pct')
          echo "::set-output name=PERCENTAGE::$PERCENTAGE"
      - if: steps.coverage_percentage.outputs.PERCENTAGE < 80
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Code coverage is too low. Current coverage is ${{steps.coverage_percentage.outputs.PERCENTAGE}}%. Minimum required coverage is 80%.'
            })
      - name: Commit Coverage Report
        uses: EndBug/add-and-commit@v9
        with:
          add: './coverage'
          author_name: '${{ github.actor }}'
          author_email: '${{ github.actor }}@users.noreply.github.com'
          committer_name: 'GitHub'
          committer_email: 'noreply@github.com'
          message: 'updated coverage report'
      - if: steps.coverage_percentage.outputs.PERCENTAGE < 80
        run: exit 1
